### ISSUE TITLE
Roadmap/missing features

### ISSUE THREAD

**Issue by apawsey** [isc30/linq-collections#11]
Hi,  Any chance you could publish a roadmap, or other method for people to understand what's meant by "Please expect some missing features until it's finished."?

Otherwise looking excellent.

**Comment by isc30** [comment]
Hi, thanks for your comment.
I just realized that you are totally right, no one except me knows what's currently missing.
Adding this will help both contributors and users! nice idea 👍

**Comment by apawsey** [comment]
Haha... Thanks for the 👍 
Yeah, so far I'm loving this... easy approach, totally intuitive for anyone having used linq before.  Will happily contribute once I know the status of things!

Think you've got a good thing going here!

**Comment by isc30** [comment]
I created a project with current status of the things, can be found [HERE](https://github.com/isc30/linq-collections/projects/1)
For first version, missing features are: `skipWhile, sequenceEquals, longCount, join, intersect, groupJoin, toLookup`. I would really love to see some contribution 😄 maybe easier thing for start is `sequenceEquals`

**Comment by kutyel** [comment]
@apawsey or you could just use a *decent* LinQ implementation like [this](https://github.com/kutyel/linq.ts) one 😉

**Comment by isc30** [comment]
that's lame, let the users (and benchmarks) decide which one is better 🤣

**Comment by kutyel** [comment]
Yeah I haven't seen the benchmarks but yours is **3x more code** and therefore more useless code in the bundle, compare [this](https://bundlephobia.com/result?p=linq-collections@1.0.242) with [this](https://bundlephobia.com/result?p=linqts@1.10.0) 😂

**Comment by isc30** [comment]
no worries, there we go:

![#5fba7d](https://placehold.it/15/5fba7d/000000?text=+) **linq-collections**: 116 ops/s
```
const list = new LinqCollections.List(data); // 100k elements
const array = list.distinct().toArray();
```

![#f03c15](https://placehold.it/15/f03c15/000000?text=+) **linq.ts**: 0.18 ops/s
```
const list = new LinqTs.List(data); // 100k elements
const array = list.Distinct();
```

**Comment by isc30** [comment]
i'll be adding a benchmarkt project, thanks for the idea 👍

**Comment by apawsey** [comment]
Well I can tell you I picked this over yours @kutyel because yours has only lists... I wanted different types of collections.  I don't think you can really claim to have a linq implementation if you only support one collection type... I guess you can have a lists of other types of things, but doesn't feel right to me.  And to be fair... the benchmarks do kinda speak for themselves.
