### ISSUE TITLE
Readonly collections?

### ISSUE THREAD

**Issue by apawsey** [isc30/linq-collections#12]
Hey...

I'm still getting busy trying to add contributions, don't think I've forgotten :smile:

In the meantime, I just wondered if you've thought about adding 'readonly' collections?  I know it's never going to be exactly perfect in the typescript/javascript world, but it's a nice addition to imply usage to users of exposed properties.

Thanks.

**Comment by isc30** [comment]
Hi 😄

There is already an `IQueryable<T>` interface that abstracts all readonly methods from all collection types.
Is that what you need? if not, please give me an example of your proposal

Thanks a lot ;D

**Comment by isc30** [comment]
I splitted `IList` and `IDictionary` into different interfaces:

`IReadOnlyList<T>`, `IList<T>` (extends readonly list)

`IReadOnlyDictionary<K,T>`, `IDictionary<K,T>` (extends readonly dictionary)

Both `IList` and `IDictionary` have `asReadOnly()` method (simple internal cast)
