### ISSUE TITLE
I cloned the source and a error has occur.

### ISSUE THREAD

**Issue by rodrigoce** [isc30/linq-collections#44]
I'm using tsc 3.2.2

after call npm install
----------------------
src/Collections.ts:1004:13 - error TS2322: Type '"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"' is not assignable to type 'Type'.
  Type '"bigint"' is not assignable to type 'Type'.

1004             this.keyType = typeof key;
                 ~~~~~~~~~~~~

**Comment by isc30** [comment]
Oh, please try removing the "bigint" part. It shouldn't be there

**Comment by isc30** [comment]
I cannot find the line that causes the error. This is the current implementation of `Type`:

https://github.com/isc30/linq-collections/blob/master/src/Types.ts#L7

**Comment by AleksandrAlpatskov** [comment]
It is an upcoming feature for Typescript >=3.2 . You only need to add the "bigint" to the Type. 
for more Information look here https://devblogs.microsoft.com/typescript/announcing-typescript-3-2/

**Comment by isc30** [comment]
oh I see, thanks for the heads up. Do you want to make a PR for it or you
prefer if I do it directly?

**Comment by isc30** [comment]
thanks for reminding me to close this
