### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by triforcely** [isc30/linq-collections#9]
This library looks very promising, however it is missing a license file and license in package.json. This might throw off potential users.

**Comment by isc30** [comment]
Hi! thanks a lot for pointing that.
I need to investigate about license types etc because I have no idea.
Any suggestions?

**Comment by isc30** [comment]
I went with MIT

**Comment by triforcely** [comment]
MIT is great for open-source. Good choice 🙂

**Comment by isc30** [comment]
thanks a lot!
